package com.grupo.integrador.gui;

import com.grupo.integrador.logic.*;
import javax.swing.SwingUtilities;


public class LoginForm extends javax.swing.JFrame {

    public LoginForm(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
        initComponents();
    }

    /**
     This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JRadioButton();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoID = new javax.swing.JTextField();
        btnLogin = new java.awt.Button();
        btnRegister = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("LoginFrame"); // NOI18N
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Noto Sans Mono", 1, 36)); // NOI18N
        lblTitulo.setText("LIBRERIA");
        lblTitulo.setFocusable(false);

        btnAdmin.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAdminItemStateChanged(evt);
            }
        });

        campoTextoNombre.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        campoTextoNombre.setText("Nombre");
        campoTextoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTextoNombreFocusGained(evt);
            }
        });
        campoTextoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTextoNombreMouseClicked(evt);
            }
        });
        campoTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreActionPerformed(evt);
            }
        });

        campoTextoID.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        campoTextoID.setText("ID");
        campoTextoID.setHighlighter(null);
        campoTextoID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTextoIDMouseClicked(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        btnLogin.setLabel("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        btnRegister.setLabel("Registrarte");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoTextoID, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNombre)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTextoIDMouseClicked
        if (campoTextoID.getText().equals("ID")) {
            campoTextoID.setText("");
        }
    }//GEN-LAST:event_campoTextoIDMouseClicked

    private void campoTextoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTextoNombreFocusGained
        if (campoTextoNombre.getText().equals("Nombre")) {
            campoTextoNombre.setText("");
        }
    }//GEN-LAST:event_campoTextoNombreFocusGained

    private void campoTextoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTextoNombreMouseClicked
        if (campoTextoNombre.getText().equals("Nombre")) {
            campoTextoNombre.setText("");
        }
    }//GEN-LAST:event_campoTextoNombreMouseClicked

    private void btnAdminItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAdminItemStateChanged
        adminToggle = btnAdmin.isSelected();
    }//GEN-LAST:event_btnAdminItemStateChanged

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
        String nombre = campoTextoNombre.getText();
        String id = campoTextoID.getText();

        if (nombre.equals("Nombre") || id.equals("ID")) return;

        Usuario newUser = new Usuario(nombre, id, adminToggle);

        if (biblioteca.usuarioExiste(id)) return;
        
        if (!biblioteca.agregarUsuario(newUser)) return;

        System.out.println("Welcome new user: " + newUser.getNombre());
        openPanel(newUser);


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String nombre = campoTextoNombre.getText();
        String id = campoTextoID.getText();

        if (!biblioteca.usuarioExiste(nombre, id)) return;

        Usuario user = biblioteca.getUsuario(nombre, id);
        openPanel(user);

    }//GEN-LAST:event_btnLoginActionPerformed

    private void campoTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreActionPerformed
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_campoTextoNombreActionPerformed

    private void openPanel(Usuario user) {
        SwingUtilities.invokeLater(() -> {
            PanelForm panelForm = new PanelForm(biblioteca, user);
            this.setVisible(false);
            panelForm.setVisible(true);
        });
    }
    
    private boolean adminToggle;
    private final Biblioteca biblioteca;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAdmin;
    private java.awt.Button btnLogin;
    private java.awt.Button btnRegister;
    private javax.swing.JTextField campoTextoID;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
