package com.grupo.integrador.gui;

import com.grupo.integrador.logic.Biblioteca;
import com.grupo.integrador.logic.Usuario;
import javax.swing.SwingUtilities;

public class PanelForm extends javax.swing.JFrame {

    public PanelForm(Biblioteca biblioteca, Usuario usuario) {
        this.usuario = usuario;
        this.biblioteca = biblioteca;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblInv = new javax.swing.JLabel();
        lvlRes = new javax.swing.JLabel();
        lblSol = new javax.swing.JLabel();
        lblversion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1240, 980));

        lblUsername.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        lblUsername.setText("Bienvenido " + usuario.getNombre());
        lblUsername.setPreferredSize(new java.awt.Dimension(171, 96));

        lblTitle.setFont(new java.awt.Font("Noto Sans Mono", 1, 36)); // NOI18N
        lblTitle.setText("LIBRERIA");

        btnInventario.setText("Libros");
        btnInventario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnInventarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnInventarioFocusLost(evt);
            }
        });
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventarioMouseExited(evt);
            }
        });
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnReservas.setText("Reservas");
        btnReservas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnReservasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnReservasFocusLost(evt);
            }
        });
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReservasMouseExited(evt);
            }
        });
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        btnSolicitudes.setText("Solicitados");
        btnSolicitudes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSolicitudesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSolicitudesFocusLost(evt);
            }
        });
        btnSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseExited(evt);
            }
        });
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        btnLogout.setText("Cerrar Sesion");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblInv.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        lblInv.setText("Abrir inventario");
        lblInv.setEnabled(false);
        lblInv.setFocusable(false);
        lblInv.setPreferredSize(new java.awt.Dimension(171, 96));

        lvlRes.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        lvlRes.setText("Mostrar libros reservados");
        lvlRes.setEnabled(false);
        lvlRes.setFocusable(false);
        lvlRes.setPreferredSize(new java.awt.Dimension(171, 96));

        lblSol.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        lblSol.setText("Mostrar libros solicitados");
        lblSol.setEnabled(false);
        lblSol.setFocusable(false);
        lblSol.setPreferredSize(new java.awt.Dimension(171, 96));

        lblversion.setFont(new java.awt.Font("Noto Sans Mono", 0, 12)); // NOI18N
        lblversion.setText("v1.0");
        lblversion.setPreferredSize(new java.awt.Dimension(171, 96));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblversion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnInventario)
                                    .addComponent(btnReservas)
                                    .addComponent(btnSolicitudes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lvlRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblversion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventario)
                    .addComponent(lblInv, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlRes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSol, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SwingUtilities.invokeLater(() -> {
            LoginForm loginForm = new LoginForm(biblioteca);
            this.setVisible(false);
            loginForm.setVisible(true);
        });
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        SwingUtilities.invokeLater(() -> {
            InventarioForm inventarioForm = new InventarioForm(biblioteca, usuario);
            this.setVisible(false);
            inventarioForm.setVisible(true);
        });

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        SwingUtilities.invokeLater(() -> {
            ReservasForm reservasForm = new ReservasForm(biblioteca, usuario);
            reservasForm.setVisible(true);
        });

    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        SwingUtilities.invokeLater(() -> {
            Solicitudesform solicitudesForm = new Solicitudesform(biblioteca, usuario);
            solicitudesForm.setVisible(true);
        });
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void btnInventarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInventarioFocusGained
        lblInv.setEnabled(true);
    }//GEN-LAST:event_btnInventarioFocusGained

    private void btnInventarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInventarioFocusLost
        lblInv.setEnabled(false);
    }//GEN-LAST:event_btnInventarioFocusLost

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        lblInv.setEnabled(true);
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        lblInv.setEnabled(false);
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnReservasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnReservasFocusGained
        lvlRes.setEnabled(true);
    }//GEN-LAST:event_btnReservasFocusGained

    private void btnReservasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnReservasFocusLost
        lvlRes.setEnabled(false);
    }//GEN-LAST:event_btnReservasFocusLost

    private void btnReservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseEntered
        lvlRes.setEnabled(true);
    }//GEN-LAST:event_btnReservasMouseEntered

    private void btnReservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseExited
        lvlRes.setEnabled(false);
    }//GEN-LAST:event_btnReservasMouseExited

    private void btnSolicitudesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSolicitudesFocusGained
        lblSol.setEnabled(true);
    }//GEN-LAST:event_btnSolicitudesFocusGained

    private void btnSolicitudesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSolicitudesFocusLost
        lblSol.setEnabled(false);
    }//GEN-LAST:event_btnSolicitudesFocusLost

    private void btnSolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseEntered
        lblSol.setEnabled(true);
    }//GEN-LAST:event_btnSolicitudesMouseEntered

    private void btnSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseExited
        lblSol.setEnabled(false);
    }//GEN-LAST:event_btnSolicitudesMouseExited

    private final Biblioteca biblioteca;
    private final Usuario usuario;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JLabel lblInv;
    private javax.swing.JLabel lblSol;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblversion;
    private javax.swing.JLabel lvlRes;
    // End of variables declaration//GEN-END:variables

}
